spring.application.name=KeyStone_Banking_Application
spring.datasource.url=jdbc:mysql://root:XgkXrMnKOvzoyWZHNRccDsqmACByHHSI@mainline.proxy.rlwy.net:24314/railway
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update 

#send grid api key 
#sendgrid.api.key=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